CREATE DATABASE IF NOT EXISTS petsnode;
USE petsnode;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS species;
CREATE TABLE IF NOT EXISTS species(
  `id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS pets (
  id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  species_id INT(10) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  foto VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  created_at DATE NOT NULL,
  FOREIGN KEY (species_id) REFERENCES species (`id`) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS votes(
id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
pet1_id INT(10) NOT NULL,
pet2_id INT(10) NOT NULL,
`result` INT(10) NOT NULL,
created_at DATE NOT NULL,
FOREIGN KEY (pet1_id) REFERENCES pets (id) ON DELETE CASCADE,
FOREIGN KEY (pet2_id) REFERENCES pets (id) ON DELETE CASCADE
);